on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
        VV_BADGE_PATH: .github/badges/vv-code-count.svg
    name: A job to test this action
    steps:
    - uses: actions/checkout@v1
    - uses: fregante/setup-git-token@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Get 7 days past date
      id: date
      run: 
       echo "::set-output name=date::$(date -d "7 days ago" +%Y-%m-%d)"
      
    - name: Generate a Vera code Severity Count
      id: open_vvcode_count
      run: |
        export VV_ISSUE_COUNT=`curl -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -H "User-Agent *" -H "Accept: application/vnd.github.v3+json" -s  https://api.github.com/search/issues?q=repo:${{ github.repository }}++is:open+is:issue+created:%3C%3D${{ steps.date.outputs.date }} | jq --raw-output '[[.items[] | .title | capture("(?<Sev>Severity [0-9]+)")  ] | group_by(.Sev) | map({ key: .[0].Sev, value: "\(length)"})    | from_entries]'`
        echo "Vere Vulnerability Count = ${VV_ISSUE_COUNT}"
        export highSeverity=`echo ${VV_ISSUE_COUNT} | jq '.[]."Severity 4"'`
        export veryHighSeverity=`echo ${VV_ISSUE_COUNT} | jq '.[]."Severity 5"'`
        echo "Very High Count = [[ ! -z ${veryHighSeverity} ]] && 100 || ${veryHighSeverity} "
        echo "High Count = ${highSeverity}"
        echo "##[set-output name=veryHighSeverity;]${veryHighSeverity}"
        echo "##[set-output name=highSeverity;]${highSeverity}"
        
    - name: Format a Vera code Severity Count
      id: formatVVBadge
      run: |
        echo "::set-output name=veryHighSeverityCount::Very High:0"
        echo "::set-output name=highSeverityCount::High:0"
        if [[ "${{ steps.open_vvcode_count.outputs.veryHighSeverity }}" != null ]]; then
          echo "1.."
          echo "::set-output name=veryHighSeverityCount::Very High:${{ steps.open_vvcode_count.outputs.veryHighSeverity }}"
        fi
        
        if [[ "${{ steps.open_vvcode_count.outputs.highSeverity }}" !=null ]]; then
          echo "2.."
          echo "::set-output name=highSeverityCount::High:${{ steps.open_vvcode_count.outputs.highSeverity }}"
        fi
        
        echo "Formatted Very High Count = ${{ steps.formatVVBadge.outputs.veryHighSeverityCount }}"
        echo "Formatted High Count = ${{ steps.formatVVBadge.outputs.highSeverityCount }}"   
