on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
        VV_BADGE_PATH: .github/badges/vv-code-count.svg
    name: A job to test this action
    steps:
    - uses: actions/checkout@v1
    - uses: fregante/setup-git-token@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Get 7 days past date
      id: date
      run: 
       echo "::set-output name=date::$(date -d "7 days ago" +%Y-%m-%d)"
      
    - name: Generate a Vera code Severity Count
      id: open_vvcode_count
      run: |
        # Generates a workflow output named `vvCount`, change color to 'green' if count is empty
        export VV_ARRAY=`curl -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -H "User-Agent *" -H "Accept: application/vnd.github.v3+json" -s  https://api.github.com/search/issues?q=repo:${{ github.repository }}++is:open+is:issue+created:%3E%3D${{ steps.date.outputs.date }} | jq --raw-output '[.items[] | .title ]'`
        #echo "Vere Vulnerability Array = ${VV_ARRAY}"
        for Item in ${VV_ARRAY} ;
        do
        #echo $Item
        if [[ $Item == *"$Severity 4"* ]]; then
        echo "Severity-4"
        elif [[ $Item == *"$Severity 3"* ]]; then
        echo "Severity-3"
        fi
        done
