on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
        VV_BADGE_PATH: .github/badges/vv-code-count.svg
    name: A job to test this action
    steps:
    - uses: actions/checkout@v1
    - uses: fregante/setup-git-token@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Get 7 days past date
      id: date
      run: 
       echo "::set-output name=date::$(date -d "7 days ago" +%Y-%m-%d)"
      
    - name: Generate a Vera code Severity Count
      id: open_vvcode_count
      run: |
        export VV_ISSUE_COUNT=`curl -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -H "User-Agent *" -H "Accept: application/vnd.github.v3+json" -s  https://api.github.com/search/issues?q=repo:${{ github.repository }}++is:open+is:issue+created:%3C%3D${{ steps.date.outputs.date }} | jq --raw-output '[[.items[] | .title | capture("(?<Sev>Severity [0-9]+)")  ] | group_by(.Sev)[] | {(.[0].Sev): "\(length)"}] | sort_by(.Key) | reverse'`
        echo "Vere Vulnerability Count = ${VV_ISSUE_COUNT}"
        export highSeverity=`echo ${VV_ISSUE_COUNT} | jq '.[]."Severity 4"'`
        export veryHighSeverity=`echo ${VV_ISSUE_COUNT} | jq '.[]."Severity 5"'`
        echo "Very High Count = ${veryHighSeverity}"
        echo "High Count = ${highSeverity}"
       
