on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
        BADGE_ROOT_PATH: .github/badges
        BADGE_PATH: open-pr-count.svg
        DEPENDS_BADGE_PATH: depend-badge.svg
        CC_BADGE_PATH: jacoco-code-coverage.svg
        RELEASE_PATH: release.svg
        VV_BADGE_PATH: vv-code-count.svg
    name: A job to test this action
    steps:
    - uses: actions/checkout@v1
    - uses: fregante/setup-git-token@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Run Tests
      run: ./gradlew clean test jacocoTestReport -i
      if: ${{ true }}

    - name: Generate JaCoCo Badge
      id: jacoco
      if: ${{ true }}
      uses: cicirello/jacoco-badge-generator@v2.1.0
      with:
          generate-branches-badge: true
          jacoco-csv-file: build/reports/tests/test/jacocoTestReport.csv
          
    - name: Get 7 days past date
      id: date
      run: 
       echo "::set-output name=date::$(date -d "7 days ago" +%Y-%m-%d)"
      
    - name: Generate a PR OPEN COUNT
      id: open_pr_count
      run: |
        # Generates a GitHub Workflow output named `lines`
        export PR_COUNT=`curl -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -H "User-Agent *" -H "Accept: application/vnd.github.v3+json" -s  https://api.github.com/search/issues?q=repo:${{ github.repository }}++is:open+is:pr+created:%3E%3D${{ steps.date.outputs.date }} | jq '.items | length'`
        echo "##[set-output name=prCount;]${PR_COUNT}"

        echo "Open PR Count = ${PR_COUNT}"
       
        # Create the directory where badge will be saved, if needed
        mkdir -p "${{ env.BADGE_ROOT_PATH }}/${{ env.BADGE_PATH }}%/*"
       
    - name: Generate a Vera code Severity Count
      id: open_vvcode_count
      run: |
        export VV_ISSUE_COUNT=`curl -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -H "User-Agent *" -H "Accept: application/vnd.github.v3+json" -s  https://api.github.com/search/issues?q=repo:${{ github.repository }}++is:open+is:issue+created:%3C%3D${{ steps.date.outputs.date }} | jq --raw-output '[[.items[] | .title | capture("(?<Sev>Severity [0-9]+)")  ] | group_by(.Sev) | map({ key: .[0].Sev, value: "\(length)"})    | from_entries]'`
        echo "Vere Vulnerability Count = ${VV_ISSUE_COUNT}"
        export highSeverity=`echo ${VV_ISSUE_COUNT} | jq -r '.[]."Severity 41" // 0'`
        export veryHighSeverity=`echo ${VV_ISSUE_COUNT} | jq -r '.[]."Severity 5" // 0'`
        echo "Very High Count = ${veryHighSeverity}"
        echo "High Count = ${highSeverity}"
        echo "##[set-output name=veryHighSeverity;]${veryHighSeverity}"
        echo "##[set-output name=highSeverity;]${highSeverity}"
       
    - name: Format a Vera code Severity Count
      id: formatVeryHighSeverityCount
      run: |
        if [[ ${{ steps.open_vvcode_count.outputs.veryHighSeverity}} > 0 ]]; then
           echo "::set-output name=veryHighSeverityColor::red"
        else
           echo "::set-output name=veryHighSeverityColor::green"
        fi
       
        if [[ ${{ steps.open_vvcode_count.outputs.highSeverity}} > 0 ]]; then
           echo "::set-output name=highSeverityColor::red"
         else
           echo "::set-output name=highSeverityColor::green"
        fi 
        
    - name: Generate VV color code
      id: displayVVCode
      run: |
        echo "Formatted Very High Count = ${{ steps.open_vvcode_count.outputs.veryHighSeverity }}"
        echo "Formatted High Count = ${{ steps.open_vvcode_count.outputs.highSeverity }}"
        export VHColor=`[ ${{ steps.open_vvcode_count.outputs.veryHighSeverity }} -eq 0 ] && echo "green" || echo "red"`
        export HColor=`[ ${{ steps.open_vvcode_count.outputs.highSeverity }} -eq 0 ] && echo "green" || echo "red"`
        echo "##[set-output name=veryHighSeverityColor;]${VHColor}"
        echo "##[set-output name=highSeverityColor;]${HColor}"
        mkdir -p "${{ env.BADGE_ROOT_PATH }}/${{ env.VV_BADGE_PATH }}%/*"
        
    - name: Generate a dependencies count
      id: dependencies_count
      run: |
        export COUNT=`curl -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -H "User-Agent *" -H "Accept: application/vnd.github.v3+json" -s  https://api.github.com/search/issues?q=is:open%20is:pr%20repo:${{ github.repository }}%20label:dependencies | jq .total_count`
        echo "${COUNT}"
        export DEPENDENCIES=`[ ${COUNT} -gt 0 ] && echo "${COUNT} out of date" || echo "up to date"`
        export DEPENDENCIES_COLOR=`[ ${COUNT} -gt 0 ] && echo "red" || echo "green"`
        echo "${DEPENDENCIES}"
        echo "${DEPENDENCIES_COLOR}"
        echo "##[set-output name=depends;]${DEPENDENCIES}"
        echo "##[set-output name=dependscolor;]${DEPENDENCIES_COLOR}"
        
        echo "Dependencies Count = ${COUNT}"
        
        # Create the directory where badges will be saved, if needed
        mkdir -p "${{ env.BADGE_ROOT_PATH }}/${{ env.DEPENDS_BADGE_PATH }}%/*"
        
    - name: Generate a coverage
      if: ${{ true }}
      id: code_coverage
      env:
          JACOCO_COVERAGE: ${{ steps.jacoco.outputs.coverage }}
      run: |
        #export COVERAGE_PERCENTAGE=`printf "%.2f" '${{ steps.jacoco.outputs.coverage }}'`
        export INTERIM_COVERAGE_PERCENTAGE=`echo ${{ steps.jacoco.outputs.coverage }} \* 100 | bc -l`
        export COVERAGE_PERCENTAGE=`printf "%.2f" ${INTERIM_COVERAGE_PERCENTAGE}`
        echo "coverage = ${COVERAGE_PERCENTAGE}"
        echo "##[set-output name=codeCoverage;]${COVERAGE_PERCENTAGE} %"
        # Create the directory where badges will be saved, if needed
        mkdir -p "${{ env.BADGE_ROOT_PATH }}/${{ env.CC_BADGE_PATH }}%/*"
        
    - name: Get latest release details
      id: release
      run: |
        # Generates a GitHub Workflow output named `releaseName`
        export RELEASE_NAME=`curl -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -H "User-Agent *" -H "Accept: application/vnd.github.v3+json" -s  https://api.github.com/repos/${{ github.repository }}/releases/latest | jq -r .name`
        echo "##[set-output name=releaseName;]${RELEASE_NAME}"
        export RELEASE=`echo "Release: ${RELEASE_NAME} "`
        export RELEASE_COLOR=`echo "green"`
        echo "Latest Release name = ${RELEASE_NAME}"
        echo "##[set-output name=depends;]${RELEASE}"
        echo "##[set-output name=dependscolor;]${RELEASE_COLOR}"
        
        # Create the directory where issue badge will be saved, if needed
        mkdir -p "${{ env.BADGE_ROOT_PATH }}/${{ env.RELEASE_PATH }}%/*"
        
    # Use the output from the `open_pr_count` step
    - name: Generate the Open PR count badge SVG image
      uses: emibcn/badge-action@v1
      id: badge
      with:
        label: 'Open Pull Requests'
        status: ${{ steps.open_pr_count.outputs.prCount }}
        color: ${{ steps.open_pr_count.outputs.prCount == 0 && 'green' || 'blue' }}
        path: ${{ env.BADGE_ROOT_PATH }}/${{ env.BADGE_PATH }}
        
    # Use the output from the `open_vvcode_count` step
    - name: Generate the Vera code count badge SVG image
      uses: emibcn/badge-action@v1
      id: vvbadge
      with:
        label: 'Vera Code Count'
        status: Very High:${{ steps.open_vvcode_count.outputs.veryHighSeverity }},High:${{ steps.open_vvcode_count.outputs.highSeverity }}
        color: '${{ steps.displayVVCode.outputs.veryHighSeverityColor }},${{ steps.displayVVCode.outputs.highSeverityColor }}'
        path: ${{ env.BADGE_ROOT_PATH }}/${{ env.VV_BADGE_PATH }}

    # Use the output from the 'jacoco' step
    - name: Generate the Code Coverage badge SVG image
      if: ${{ true }}
      uses: emibcn/badge-action@v1
      id: badgeJJ
      with:
        label: 'JACOCO Code Coverage'
        status: ${{ steps.code_coverage.outputs.codeCoverage }}
        color: ${{ steps.code_coverage.outputs.codeCoverage > 75 && 'green' || 'red' }}
        path: ${{ env.BADGE_ROOT_PATH }}/${{ env.CC_BADGE_PATH }}
 
    - name: Generate the dependencies badge SVG image
      uses: emibcn/badge-action@v1
      id: deps
      with:
        label: 'dependencies'
        status: ${{ steps.dependencies_count.outputs.depends }}
        color: ${{ steps.dependencies_count.outputs.dependscolor }}
        path: ${{ env.BADGE_ROOT_PATH }}/${{ env.DEPENDS_BADGE_PATH }}
    
    - name: Generate release badge SVG image
      uses: emibcn/badge-action@v1
      id: releaseBadge
      with:
        label: 'Latest Release'
        status: ${{ steps.release.outputs.releaseName }}
        color: 'blue,555,daf'
        path: ${{ env.BADGE_ROOT_PATH }}/${{ env.RELEASE_PATH }}
       
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch
    - name: Commit badge
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add *.svg
        git commit -m "Add/Update badges" || true
    - name: Push badge commit
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ steps.extract_branch.outputs.branch }}
