on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
        VV_BADGE_PATH: .github/badges/vv-code-count.svg
    name: A job to test this action
    steps:
    - uses: actions/checkout@v1
    - uses: fregante/setup-git-token@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Get 7 days past date
      id: date
      run: 
       echo "::set-output name=date::$(date -d "7 days ago" +%Y-%m-%d)"
      
    - name: Generate a Vera code Severity Count
      id: open_vvcode_count
      run: |
        export VV_ISSUE_COUNT=`curl -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -H "User-Agent *" -H "Accept: application/vnd.github.v3+json" -s  https://api.github.com/search/issues?q=repo:${{ github.repository }}++is:open+is:issue+created:%3E%3D${{ steps.date.outputs.date }} | jq --raw-output '[[.items[] | .title | capture("(?<Sev>Severity [0-9]+)") | if .Sev == "Severity 4" then .Sev="Very High" elif .Sev == "Severity 3" then .Sev="High" else "many" end ] | group_by(.Sev)[] | {Key: "\(.[0].Sev):\(length)"}] | sort_by(.Key) | reverse|  map(.Key) | join(",")'`
        echo "Vere Vulnerability Count = ${VV_ISSUE_COUNT}"
        export ff=`echo ${VV_ISSUE_COUNT} | grep -e [1-9]`
        export color=`$ff && echo "green" || echo "red"`
        export VV_COUNT=`$ff && echo "No Vulnerabilities" || echo $VV_ISSUE_COUNT`
        echo "##[set-output name=vvCount;]${VV_COUNT}"
        echo "##[set-output name=vvBadgeColor;]${color}"
        echo "Vere Code Count = ${VV_COUNT}"
        echo "Vere Code Color = ${color}"
        if [[ "${VV_ISSUE_COUNT}" == *"$Very High"* ]]; then echo 'sfsdf' fi
    
       
