on: [push]

jobs:
  badge_job:
    runs-on: ubuntu-latest
    name: Testing BYOB
    steps:
      - id: date
        run: echo "##[set-output name=data;]$(date)"
      - id: machine
        run: echo "##[set-output name=data;]$(hostname)"
      - id: size
        run: echo "##[set-output name=data;]$(du -sh . | sed 's/[^0-9a-zA-Z]//g')"
      - name: Time badge
        uses: actions/checkout@master
        with:
          NAME: time
          LABEL: 'Updated at'
          STATUS: ${{ steps.date.outputs.data }}
          COLOR: 00EEFF
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Machine Badge
        uses: actions/checkout@master
        with:
          NAME: machine
          LABEL: 'Hostname'
          STATUS: ${{ steps.machine.outputs.data }}
          COLOR: FFC0CB
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Size Badge
        uses: actions/checkout@master
        with:
          NAME: size
          LABEL: 'Repo Size'
          STATUS: ${{ steps.size.outputs.data }}
          COLOR: 00FF00
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: First Icon
        uses: actions/checkout@master
        with:
          NAME: github
          LABEL: 'GitHub'
          ICON: 'github'
          STATUS: 'BYOBTest'
          COLOR: blue
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Labeless Icon
        uses: actions/checkout@master
        with:
          NAME: git
          ICON: 'git'
          STATUS: 'Git'
          COLOR: red
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Custom Icon
        uses: actions/checkout@master
        with:
          NAME: custom
          ICON: 'https://simpleicons.now.sh/counter-strike/e43'
          STATUS: 'Custom Icons'
          COLOR: red
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
