on: [push]

jobs:
  badge_job:
    runs-on: ubuntu-latest
    name: Testing BYOB
    steps:
      - name: Time badge
        uses: emibcn/badge-action@v1
        with:
          label: 'Test coverage'
          status: '53.4%'
          color: 'blue,555,daf'
          path: 'master/test-badge.svg'
