name: Reuse Workflow Rest CI Build
on:
 push:

jobs:
  rest_ci_build_call_test:
   uses:  RahulVadisetty91/RestService
   with:
    workflow: CI Build
    repo: RahulVadisetty91/Reusable_Repository
    token: ${{ secrets.PERSONAL_TOKEN }}
