name: Reuse Workflow Rest CI Build
on:
 push:
 workflow_dispatch:
 workflow_call:

jobs:
  rest_ci_build_call_test:
   uses: RahulVadisetty91/Reusable_Repository/tree/main/workflow_templates/java-cicd-workflow/workflows@main
   with:
    workflow: CI Build
    repo: RahulVadisetty91/Reusable_Repository
    token: ${{ secrets.PERSONAL_TOKEN }}
