name: Reuse Workflow Rest CI Build
on:
 push:

jobs:
  rest_ci_build_call_test:
   uses:  RahulVadisetty91/RestService
   with:
    workflow: Workflow_test@0519683ed2ef01616c7a606fdb7937ce68509ac1
    repo: RahulVadisetty91/Reusable_Repository
    token: ${{ secrets.PERSONAL_TOKEN }}
