name: Reuse Workflow Rest CI Build
on:
 push:
 workflow_dispatch:
 workflow_call:

jobs:
  rest_ci_build_call_test:
   uses:  benc-uk/workflow-dispatch@v1
   with:
    workflow: build.yml
    repo: RahulVadisetty91/Reusable_Repository/workflow_templates/java-cicd-workflow/workflows/
    token: ${{ secrets.PERSONAL_TOKEN }}
