name: Reuse Workflow Rest CI Build
on:
 push:
 workflow_dispatch:
 workflow_call:

jobs:
  rest_ci_build_call_test:
   uses: RestService/workflow-dispatch@resuable_repo
   with:
    workflow: CI Build
    repo: RahulVadisetty91/Reusable_Repository
    token: ${{ secrets.PERSONAL_TOKEN }}
