name: Reuse Workflow Rest CI Build
on:
 push:
 workflow_dispatch:
 workflow_call:

jobs:
  rest_ci_build_call_test:
   uses:  RahulVadisetty91/RestService@resuable_repo
   with:
    workflow: build
    repo: RahulVadisetty91/Reusable_Repository
    token: ${{ secrets.PERSONAL_TOKEN }}
