name: Reuse Workflow Rest CI Build
on: [push]

jobs:
  rest_ci_build_call_test:
   uses: convictional/trigger-workflow-and-wait@master
   with:
    owner:  RahulVadisetty91
    repo:  Reusable_Repository
    github_token: ${{ secrets.GITHUB_TOKEN  }}
    workflow_file_name: build.yml
