name: Reuse Workflow Rest CI Build
on:
 push:
 workflow_dispatch:
 workflow_call:

jobs:
  rest_ci_build_call_test:
   uses:  Reusable_Repository/workflow_templates/java-cicd-workflow/workflows/build.yml 
   with:
    workflow: Some Workflow
    repo:  RahulVadisetty91/Reusable_Repository
    token: ${{ secrets.PERSONAL_TOKEN }}
