name: Reuse Workflow Rest CI Build
on:
 push:

jobs:
  rest_ci_build_call_test:
   uses:  benc-uk/workflow-dispatch@v1
   with:
    workflow: Workflow_test
    repo: RahulVadisetty91/Reusable_Repository
    token: ${{ secrets.PERSONAL_TOKEN }}
