# This workflow will check the status of PRs

name: Gradle Package

on: [push]

jobs:
  stats:
    runs-on: ubuntu-latest
    steps:
      - name: Run pull request stats
        uses: RahulVadisetty91/RestService@develop/pipeline
        with:
          token: ${{ secrets.ADD_A_PERSONAL_ACCESS_TOKEN }}
          period: 7
          charts: true
          disable-links: true
          sort-by: 'COMMENTS'
