on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: A job to test this action
    steps:
    - uses: actions/checkout@v1
    - uses: fregante/setup-git-token@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Run Tests
      run: ./gradlew test

    - name: Run Test Coverage
      run: ./gradlew jacocoTestReport

    - name: Generate JaCoCo Badge
      id: jacoco
      uses: cicirello/jacoco-badge-generator@v2
      with:
          generate-branches-badge: true
          jacoco-csv-file: build/reports/jacoco/test/jacocoTestReport.csv
          
    - name: Generate a coverage value
      id: coverage
      run: |
        # Generates a GitHub Workflow output named `lines`
        export COVERAGE=`curl -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -H "User-Agent *" -H "Accept: application/vnd.github.v3+json" -s  https://api.github.com/repos/RahulVadisetty91/RestService/pulls | jq length`
        echo "##[set-output name=lines;]${COVERAGE}"

        export COUNT=`curl -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -H "User-Agent *" -H "Accept: application/vnd.github.v3+json" -s  https://api.github.com/search/issues?q=is:open%20is:pr%20repo:RahulVadisetty91/RestService%20label:dependencies | jq .total_count`
        echo "${COUNT}"
        export DEPENDENCIES=`[ ${COUNT} -gt 0 ] && echo "${COUNT} out of date" || echo "up to date"`
        export DEPENDENCIES_COLOR=`[ ${COUNT} -gt 0 ] && echo "red" || echo "green"`
        echo "${DEPENDENCIES}"
        echo "${DEPENDENCIES_COLOR}"
        echo "##[set-output name=depends;]${DEPENDENCIES}"
        echo "##[set-output name=dependscolor;]${DEPENDENCIES_COLOR}"
        
        echo "coverage = ${{ steps.jacoco.outputs.coverage }}"
        echo "##[set-output name=codeCoverage;]${{ steps.jacoco.outputs.coverage }}"
        
        # Create the directory where badges will be saved, if needed
        mkdir -p "${BADGE_PATH%/*}"
        mkdir -p "${CC_BADGE_PATH%/*}"
        echo "##[set-output name=path;]${BADGE_PATH}"
        echo "##[set-output name=depspath;]${DEPENDS_BADGE_PATH}"
        echo "##[set-output name=jjBadgePath;]${CC_BADGE_PATH}"
      env:
        COVERAGE: 53.5%
        DEPENDENCIES: 0
        BADGE_PATH: .github/badges/test-badge.svg
        DEPENDS_BADGE_PATH: .github/badges/depend-badge.svg
        CC_BADGE_PATH: .github/badges/temp-code-coverage.svg

    # Use the output from the `coverage` step
    - name: Generate the badge SVG image
      uses: emibcn/badge-action@v1
      id: badge
      with:
        label: 'Open Pull Requests'
        status: ${{ steps.coverage.outputs.lines }}
        color: 'blue,555,daf'
        path: ${{ steps.coverage.outputs.path }}
        
    # Use the output from the 'jacoco' step
    - name: Generate the Code Coverage badge SVG image
      uses: emibcn/badge-action@v1
      id: badgeJJ
      with:
        label: 'Code Coverage'
        status: ${{ steps.coverage.outputs.codeCoverage }}
        color: 'blue,555,daf'
        path: ${{ steps.coverage.outputs.jjBadgePath }}
 
    - name: Generate the badge SVG image
      uses: emibcn/badge-action@v1
      id: deps
      with:
        label: 'dependencies'
        status: ${{ steps.coverage.outputs.depends }}
        color: ${{ steps.coverage.outputs.dependscolor }}
        path: ${{ steps.coverage.outputs.depspath }}
        
    - name: Upload badge as artifact
      uses: actions/upload-artifact@v2
      with:
        name: badge
        path: ${{ steps.coverage.outputs.path }}
        if-no-files-found: error
        
    - name: Upload badge as artifact
      uses: actions/upload-artifact@v2
      with:
        name: badge
        path: ${{ steps.coverage.outputs.depspath }}
        if-no-files-found: error
        
    - name: Upload jacoco badge as artifact
      uses: actions/upload-artifact@v2
      with:
        name: badge
        path: ${{ steps.coverage.outputs.jjBadgePath }}
        if-no-files-found: error
  
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch
    - name: Commit badge
      env:
        BADGE: ${{ steps.coverage.outputs.path }}
        DEPSBADGE: ${{ steps.coverage.outputs.depspath }}
        CODECOVERAGEBADGE: ${{ steps.coverage.outputs.jjBadgePath }}
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add "${BADGE}"
        git add "${DEPSBADGE}"
        git commit -m "Add/Update badge"
    - name: Push badge commit
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ steps.extract_branch.outputs.branch }}
