on: push

jobs:
  checkstyle_job:
    runs-on: ubuntu-latest
    env:
        GIT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    name: Checkstyle job
    steps:
    - name: Update GitHub Profile README
      uses: theboi/github-update-readme@v1.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        header: "![Build-Java Status](https://github.com/RahulVadisetty91/RestService/actions/workflows/build.yml/badge.svg?branch=develop/pipeline)"
        subhead: "Badges"
        repoCount: 0
