name: Update READMe thru Dynamic Template

on: [push]

jobs:
  update_templates:
    name: "Update Templates"
    runs-on: ubuntu-latest
    steps:
      - name: "📥  Fetching Repository Contents"
        uses: actions/checkout@main

      - name: "💾  Github Repository Metadata"
        uses: varunsridharan/action-repository-meta@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: "💫  Dynamic Template Render"
        uses: varunsridharan/action-dynamic-readme@main
        with:
          GLOBAL_TEMPLATE_REPOSITORY: ${{ github.repository }}
          files: |
            DummyFile.md
            include.md=output/include.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
