on: [push]
name: Open PR Count

jobs:
  logLatestRelease:
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@master
        id: get_latest_release
        with:
          route: GET /repos/{owner}/{repo}/releases/latest
          owner: RahulVadisetty91
          repo: RestService
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: "echo latest release: ${{ steps.get_latest_release.outputs.data }}"
