# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle

name: Open PR Count

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: "Get latest release of ${{ github.repository }}"
        uses: actions/checkout@master
        with:
          url: https://my-json-server.typicode.com/typicode/demo/posts
          method: GET
      - run: $output = '${{ steps.webhook.outputs.output }}' | ConvertFrom-Json
          Write-Host "Time from output $($output.time) statusCode $($output.statusCode) data $($output.data)"
