on: [push]
name: Open PR Count

jobs:
  webrequest_test:
    runs-on: ubuntu-latest
    name: Test Open PR requests
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: GET request
        id: get-request
        uses: satak/webrequest-action@master
        with:
          url: https://api.github.com/repos/RahulVadisetty91/RestService/pulls
          method: GET
      - name: get-request output
        shell: pwsh
        run: |
          $output = '${{ steps.get-request.outputs.output }}' | ConvertFrom-Json
          


#jobs:
#  webrequest_test:
#    runs-on: ubuntu-latest
#    name: Fetch Pull details
#    steps:
#      - name: GET request
#        id: get-request
#        uses: actions/checkout@master
#        with:
#          url: https://api.github.com/repos/RahulVadisetty91/RestService/pulls
#          method: GET
#      - name: get-request output
#        shell: pwsh
#        run: |
#          $output = '${{ steps.get-request.outputs.output }}' | ConvertFrom-Json
#          $output.data



#jobs:
#  build:

#    runs-on: ubuntu-latest
#    steps:
##     - uses: actions/checkout@master
#      - name: "Get latest release of ${{ github.repository }}"
#        uses: actions/checkout@master
#       with:
#          url: https://my-json-server.typicode.com/typicode/demo/posts
#          method: GET
#      - run: $output = '${{ steps.webhook.outputs.output }}' | ConvertFrom-Json
#          Write-Host "Time from output $($output.time) statusCode $($output.statusCode) data $($output.data)"
