on: [push]
name: Open PR Count

jobs:
  webrequest_test:
    runs-on: ubuntu-latest
    name: Test POST and GET web requests
    steps:
      - name: GET request
        id: get-request
        uses: actions/checkout@master
        with:
          url: https://api.github.com/repos/RahulVadisetty91/RestService
          method: GET
      - name: get-request output
        shell: pwsh
        run: |
          $output = '${{ steps.get-request.outputs }}' | ConvertFrom-Json
          $output



#jobs:
#  build:

#    runs-on: ubuntu-latest
#    steps:
##     - uses: actions/checkout@master
#      - name: "Get latest release of ${{ github.repository }}"
#        uses: actions/checkout@master
#       with:
#          url: https://my-json-server.typicode.com/typicode/demo/posts
#          method: GET
#      - run: $output = '${{ steps.webhook.outputs.output }}' | ConvertFrom-Json
#          Write-Host "Time from output $($output.time) statusCode $($output.statusCode) data $($output.data)"
