on: [push]
name: Open PR Count

jobs:
  webrequest_test:
    runs-on: ubuntu-latest
    name: Test Open PR requests
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: GET request
        id: get-request
        uses: actions/checkout@master
        with:
          url: https://api.github.com/repos/RahulVadisetty91/RestService
          method: GET
      - name: get-request output
        shell: pwsh
        run: "echo latest release: '${{ fromJson(steps.get-request.outputs.data).open_issues }}'"
