on: [push]
name: Open PR Count

jobs:
  webrequest_test:
    runs-on: ubuntu-latest
    name: Test Open PR requests
    steps:
      - run: "echo Fetching PR Count"
      - name: "Get Open PR Count of ${{ github.repository }}"
        uses: actions/checkout@master
        id: get_latest_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          route: GET /repos/{owner}/{repo}/releases/latest
          owner: RahulVadisetty91
          repo: RestService
      - run: "echo latest release: '${{ fromJson(steps.get_latest_release.outputs.data).open_issues }}'"
