on: [push]
name: Open PR Count

jobs:
  webrequest_test:
    runs-on: ubuntu-latest
    name: Test Open PR requests
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: GET request
        id: get-request
        uses: satak/webrequest-action@master
        with:
          url: https://api.github.com/repos/RahulVadisetty91/RestService/pulls
          method: GET
      - name: get-request output
        shell: pwsh
        run: |
          $output = '${{ steps.get-request.outputs.output }}' | ConvertFrom-Json
          $output.data[0].open_issues
